from __future__ import annotations

from datetime import date
from typing import Protocol


class SecurityMasterProvider(Protocol):
    def get_active_equities(self, as_of_date: date) -> list[dict]: ...
    def resolve_isin(self, exchange: str, symbol: str, as_of_date: date) -> dict | None: ...
    def get_identifier_history(self, isin: str) -> list[dict]: ...


class MarketDataProvider(Protocol):
    def get_market_snapshot(self, isin: str, as_of_date: date) -> dict: ...
    def get_ohlcv(self, isin: str, start_date: date, end_date: date, adjusted: bool = True) -> list[dict]: ...
    def get_corporate_actions(self, isin: str, through_date: date) -> list[dict]: ...
    def get_technical_snapshot(self, isin: str, as_of_date: date) -> dict: ...


class FundamentalDataProvider(Protocol):
    def get_annual_financials(self, isin: str, through_date: date, periods: int = 6, scope: str | None = None) -> list[dict]: ...
    def get_quarterly_financials(self, isin: str, through_date: date, periods: int = 12, scope: str | None = None) -> list[dict]: ...
    def get_filing_versions(self, isin: str, through_date: date) -> list[dict]: ...
    def get_statement_scope(self, isin: str, period_end: date | None = None) -> dict: ...


class EvidenceProvider(Protocol):
    def get_company_filings(self, isin: str, published_through: date) -> list[dict]: ...
    def get_document(self, artifact_id: str) -> bytes: ...
