/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/alert-incidents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Incidents */
        get: operations["incidents_api_v1_alert_incidents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alert-incidents/{incident_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Incident Detail */
        get: operations["incident_detail_api_v1_alert_incidents__incident_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Alerts */
        get: operations["alerts_api_v1_alerts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts/{alert_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Alert Detail */
        get: operations["alert_detail_api_v1_alerts__alert_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/calibration/coverage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Calibration Coverage */
        get: operations["calibration_coverage_api_v1_calibration_coverage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/calibration/exclusions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Calibration Exclusions */
        get: operations["calibration_exclusions_api_v1_calibration_exclusions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/calibration/manifest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Calibration Manifest */
        get: operations["calibration_manifest_api_v1_calibration_manifest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/calibration/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Calibration Summary */
        get: operations["calibration_summary_api_v1_calibration_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Candidates */
        get: operations["candidates_api_v1_candidates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/candidates/{candidate_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Candidate Detail */
        get: operations["candidate_detail_api_v1_candidates__candidate_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/candidates/{candidate_id}/decisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Candidate Decisions */
        get: operations["candidate_decisions_api_v1_candidates__candidate_id__decisions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/candidates/{candidate_id}/outcomes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Candidate Outcomes */
        get: operations["candidate_outcomes_api_v1_candidates__candidate_id__outcomes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/candidates/{candidate_id}/snapshots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Candidate Snapshots */
        get: operations["candidate_snapshots_api_v1_candidates__candidate_id__snapshots_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/governance/conflicts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Governance Conflicts */
        get: operations["governance_conflicts_api_v1_governance_conflicts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/governance/correction-impacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Impacts */
        get: operations["impacts_api_v1_governance_correction_impacts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/governance/membership-history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Memberships */
        get: operations["memberships_api_v1_governance_membership_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/governance/stage-corrections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Corrections */
        get: operations["corrections_api_v1_governance_stage_corrections_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Live */
        get: operations["health_live_api_v1_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Ready */
        get: operations["health_ready_api_v1_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/market/stage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Market Stage */
        get: operations["market_stage_api_v1_market_stage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/performance/baselines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Performance Baselines */
        get: operations["performance_baselines_api_v1_performance_baselines_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/performance/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Performance Latest */
        get: operations["performance_latest_api_v1_performance_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/performance/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Performance Runs */
        get: operations["performance_runs_api_v1_performance_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/performance/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Performance Run */
        get: operations["performance_run_api_v1_performance_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/positions/coverage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Position Coverage */
        get: operations["position_coverage_api_v1_positions_coverage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/positions/coverage/{position_cycle_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Position Detail */
        get: operations["position_detail_api_v1_positions_coverage__position_cycle_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/positions/missing-data": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Position Missing */
        get: operations["position_missing_api_v1_positions_missing_data_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/positions/recovery-proposals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recovery Proposals */
        get: operations["recovery_proposals_api_v1_positions_recovery_proposals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/readiness/checks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness Checks */
        get: operations["readiness_checks_api_v1_readiness_checks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/routing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Routing */
        get: operations["routing_api_v1_routing_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/routing/conflicts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Routing Conflicts */
        get: operations["routing_conflicts_api_v1_routing_conflicts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/routing/{routing_decision_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Routing Detail */
        get: operations["routing_detail_api_v1_routing__routing_decision_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sectors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sectors */
        get: operations["sectors_api_v1_sectors_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sectors/{sector_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sector Detail */
        get: operations["sector_detail_api_v1_sectors__sector_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stocks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stocks */
        get: operations["stocks_api_v1_stocks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stocks/{symbol_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stock Detail */
        get: operations["stock_detail_api_v1_stocks__symbol_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stocks/{symbol_id}/routing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stock Routing */
        get: operations["stock_routing_api_v1_stocks__symbol_id__routing_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stocks/{symbol_id}/stage-history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stock History */
        get: operations["stock_history_api_v1_stocks__symbol_id__stage_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/limitations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** System Limitations */
        get: operations["system_limitations_api_v1_system_limitations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/readiness": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** System Readiness */
        get: operations["system_readiness_api_v1_system_readiness_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** System Version */
        get: operations["system_version_api_v1_system_version_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AlertIncidentSummary */
        AlertIncidentSummary: {
            /** Alert Code */
            alert_code: string;
            /** Alert Id */
            alert_id: string;
            /** Dedupe Key */
            dedupe_key?: string | null;
            /** Missing Field Signature */
            missing_field_signature?: string | null;
            /**
             * Occurrence Count
             * @default 1
             */
            occurrence_count: number;
            /**
             * Opened At
             * Format: date-time
             */
            opened_at: string;
            /** Position Cycle Id */
            position_cycle_id?: string | null;
            /** Recommended Operator Action */
            recommended_operator_action?: string | null;
            /** Resolved At */
            resolved_at?: string | null;
            /** Severity */
            severity: string;
            /** Status */
            status: string;
            /** Symbol Id */
            symbol_id?: string | null;
        };
        /** AlertSummary */
        AlertSummary: {
            /** Alert Code */
            alert_code: string;
            /** Alert Id */
            alert_id: string;
            /** Dedupe Key */
            dedupe_key?: string | null;
            /** Missing Field Signature */
            missing_field_signature?: string | null;
            /**
             * Opened At
             * Format: date-time
             */
            opened_at: string;
            /** Position Cycle Id */
            position_cycle_id?: string | null;
            /** Recommended Operator Action */
            recommended_operator_action?: string | null;
            /** Resolved At */
            resolved_at?: string | null;
            /** Severity */
            severity: string;
            /** Status */
            status: string;
            /** Symbol Id */
            symbol_id?: string | null;
        };
        /** ApiResponse[AlertIncidentSummary] */
        ApiResponse_AlertIncidentSummary_: {
            data: components["schemas"]["AlertIncidentSummary"];
            meta: components["schemas"]["ResponseMeta"];
        };
        /** ApiResponse[AlertSummary] */
        ApiResponse_AlertSummary_: {
            data: components["schemas"]["AlertSummary"];
            meta: components["schemas"]["ResponseMeta"];
        };
        /** ApiResponse[CalibrationManifestResponse] */
        ApiResponse_CalibrationManifestResponse_: {
            data: components["schemas"]["CalibrationManifestResponse"];
            meta: components["schemas"]["ResponseMeta"];
        };
        /** ApiResponse[CalibrationSummaryResponse] */
        ApiResponse_CalibrationSummaryResponse_: {
            data: components["schemas"]["CalibrationSummaryResponse"];
            meta: components["schemas"]["ResponseMeta"];
        };
        /** ApiResponse[CandidateDetail] */
        ApiResponse_CandidateDetail_: {
            data: components["schemas"]["CandidateDetail"];
            meta: components["schemas"]["ResponseMeta"];
        };
        /** ApiResponse[HealthResponse] */
        ApiResponse_HealthResponse_: {
            data: components["schemas"]["HealthResponse"];
            meta: components["schemas"]["ResponseMeta"];
        };
        /** ApiResponse[MarketStageResponse] */
        ApiResponse_MarketStageResponse_: {
            data: components["schemas"]["MarketStageResponse"];
            meta: components["schemas"]["ResponseMeta"];
        };
        /** ApiResponse[PerformanceSummaryResponse] */
        ApiResponse_PerformanceSummaryResponse_: {
            data: components["schemas"]["PerformanceSummaryResponse"];
            meta: components["schemas"]["ResponseMeta"];
        };
        /** ApiResponse[PositionCoverageSummary] */
        ApiResponse_PositionCoverageSummary_: {
            data: components["schemas"]["PositionCoverageSummary"];
            meta: components["schemas"]["ResponseMeta"];
        };
        /** ApiResponse[RoutingDecisionDetail] */
        ApiResponse_RoutingDecisionDetail_: {
            data: components["schemas"]["RoutingDecisionDetail"];
            meta: components["schemas"]["ResponseMeta"];
        };
        /** ApiResponse[SectorSummary] */
        ApiResponse_SectorSummary_: {
            data: components["schemas"]["SectorSummary"];
            meta: components["schemas"]["ResponseMeta"];
        };
        /** ApiResponse[StockSummary] */
        ApiResponse_StockSummary_: {
            data: components["schemas"]["StockSummary"];
            meta: components["schemas"]["ResponseMeta"];
        };
        /** ApiResponse[SystemReadinessResponse] */
        ApiResponse_SystemReadinessResponse_: {
            data: components["schemas"]["SystemReadinessResponse"];
            meta: components["schemas"]["ResponseMeta"];
        };
        /** ApiResponse[VersionResponse] */
        ApiResponse_VersionResponse_: {
            data: components["schemas"]["VersionResponse"];
            meta: components["schemas"]["ResponseMeta"];
        };
        /** ApiResponse[dict[str, str]] */
        ApiResponse_dict_str__str__: {
            /** Data */
            data: {
                [key: string]: string;
            };
            meta: components["schemas"]["ResponseMeta"];
        };
        /** ApiResponse[list[AlertIncidentSummary]] */
        ApiResponse_list_AlertIncidentSummary__: {
            /** Data */
            data: components["schemas"]["AlertIncidentSummary"][];
            meta: components["schemas"]["ResponseMeta"];
        };
        /** ApiResponse[list[AlertSummary]] */
        ApiResponse_list_AlertSummary__: {
            /** Data */
            data: components["schemas"]["AlertSummary"][];
            meta: components["schemas"]["ResponseMeta"];
        };
        /** ApiResponse[list[CandidateSnapshotResponse]] */
        ApiResponse_list_CandidateSnapshotResponse__: {
            /** Data */
            data: components["schemas"]["CandidateSnapshotResponse"][];
            meta: components["schemas"]["ResponseMeta"];
        };
        /** ApiResponse[list[CandidateSummary]] */
        ApiResponse_list_CandidateSummary__: {
            /** Data */
            data: components["schemas"]["CandidateSummary"][];
            meta: components["schemas"]["ResponseMeta"];
        };
        /** ApiResponse[list[CorrectionImpactResponse]] */
        ApiResponse_list_CorrectionImpactResponse__: {
            /** Data */
            data: components["schemas"]["CorrectionImpactResponse"][];
            meta: components["schemas"]["ResponseMeta"];
        };
        /** ApiResponse[list[DecisionContextResponse]] */
        ApiResponse_list_DecisionContextResponse__: {
            /** Data */
            data: components["schemas"]["DecisionContextResponse"][];
            meta: components["schemas"]["ResponseMeta"];
        };
        /** ApiResponse[list[GovernanceCorrectionResponse]] */
        ApiResponse_list_GovernanceCorrectionResponse__: {
            /** Data */
            data: components["schemas"]["GovernanceCorrectionResponse"][];
            meta: components["schemas"]["ResponseMeta"];
        };
        /** ApiResponse[list[OutcomeAttributionResponse]] */
        ApiResponse_list_OutcomeAttributionResponse__: {
            /** Data */
            data: components["schemas"]["OutcomeAttributionResponse"][];
            meta: components["schemas"]["ResponseMeta"];
        };
        /** ApiResponse[list[PerformanceSummaryResponse]] */
        ApiResponse_list_PerformanceSummaryResponse__: {
            /** Data */
            data: components["schemas"]["PerformanceSummaryResponse"][];
            meta: components["schemas"]["ResponseMeta"];
        };
        /** ApiResponse[list[PositionCoverageSummary]] */
        ApiResponse_list_PositionCoverageSummary__: {
            /** Data */
            data: components["schemas"]["PositionCoverageSummary"][];
            meta: components["schemas"]["ResponseMeta"];
        };
        /** ApiResponse[list[ReadinessCheckResponse]] */
        ApiResponse_list_ReadinessCheckResponse__: {
            /** Data */
            data: components["schemas"]["ReadinessCheckResponse"][];
            meta: components["schemas"]["ResponseMeta"];
        };
        /** ApiResponse[list[RoutingDecisionSummary]] */
        ApiResponse_list_RoutingDecisionSummary__: {
            /** Data */
            data: components["schemas"]["RoutingDecisionSummary"][];
            meta: components["schemas"]["ResponseMeta"];
        };
        /** ApiResponse[list[SectorSummary]] */
        ApiResponse_list_SectorSummary__: {
            /** Data */
            data: components["schemas"]["SectorSummary"][];
            meta: components["schemas"]["ResponseMeta"];
        };
        /** ApiResponse[list[StageObservation]] */
        ApiResponse_list_StageObservation__: {
            /** Data */
            data: components["schemas"]["StageObservation"][];
            meta: components["schemas"]["ResponseMeta"];
        };
        /** ApiResponse[list[StockSummary]] */
        ApiResponse_list_StockSummary__: {
            /** Data */
            data: components["schemas"]["StockSummary"][];
            meta: components["schemas"]["ResponseMeta"];
        };
        /** ApiResponse[list[SystemLimitation]] */
        ApiResponse_list_SystemLimitation__: {
            /** Data */
            data: components["schemas"]["SystemLimitation"][];
            meta: components["schemas"]["ResponseMeta"];
        };
        /** ApiResponse[list[dict[str, Any]]] */
        ApiResponse_list_dict_str__Any___: {
            /** Data */
            data: {
                [key: string]: unknown;
            }[];
            meta: components["schemas"]["ResponseMeta"];
        };
        /** CalibrationManifestResponse */
        CalibrationManifestResponse: {
            /** Configuration Hash */
            configuration_hash?: string | null;
            /** Dataset Hashes */
            dataset_hashes?: {
                [key: string]: string;
            };
            /** Date Bounds */
            date_bounds?: {
                [key: string]: unknown;
            };
            /** Manifest Id */
            manifest_id?: string | null;
            /** Migration Lineage */
            migration_lineage?: unknown[];
            /** Policy Hashes */
            policy_hashes?: {
                [key: string]: string;
            };
            /** Policy Version */
            policy_version: string;
            /** Replay Equivalent */
            replay_equivalent?: boolean | null;
            /** Reproducibility Status */
            reproducibility_status?: string | null;
            /** Row Counts */
            row_counts?: {
                [key: string]: number;
            };
            /** Schema Versions */
            schema_versions?: {
                [key: string]: string;
            };
            /** Source Hashes */
            source_hashes?: {
                [key: string]: string;
            };
        };
        /** CalibrationSummaryResponse */
        CalibrationSummaryResponse: {
            /** Class Counts */
            class_counts?: {
                [key: string]: number;
            };
            /** Date Range */
            date_range?: {
                [key: string]: unknown;
            };
            /**
             * Eligible Count
             * @default 0
             */
            eligible_count: number;
            /**
             * Excluded Count
             * @default 0
             */
            excluded_count: number;
            /** Formal Verdict */
            formal_verdict?: string | null;
            /** Largest Class Share */
            largest_class_share?: number | null;
            /** Manifest Id */
            manifest_id?: string | null;
            /**
             * Pending Count
             * @default 0
             */
            pending_count: number;
            /** Phase4 Development Ready */
            phase4_development_ready?: boolean | null;
            /** Phase4 Production Ready */
            phase4_production_ready?: boolean | null;
            /** Policy Version */
            policy_version?: string | null;
            /**
             * Quarantined Count
             * @default 0
             */
            quarantined_count: number;
            /** Regime Coverage */
            regime_coverage?: {
                [key: string]: number;
            };
            /** Scan Tier Coverage */
            scan_tier_coverage?: {
                [key: string]: number;
            };
            /** Setup Family Coverage */
            setup_family_coverage?: {
                [key: string]: number;
            };
            /** Stage Coverage */
            stage_coverage?: {
                [key: string]: unknown;
            };
            /** Top Exclusion Reasons */
            top_exclusion_reasons?: {
                [key: string]: unknown;
            }[];
            /**
             * Total Samples
             * @default 0
             */
            total_samples: number;
        };
        /** CandidateDetail */
        CandidateDetail: {
            /** Candidate Id */
            candidate_id: string;
            /** Candidate State */
            candidate_state: string;
            /** Closed At */
            closed_at?: string | null;
            /** Correction Impact Status */
            correction_impact_status?: string | null;
            /** Exchange */
            exchange: string;
            /** Followthrough Status */
            followthrough_status?: string | null;
            /**
             * History Completeness
             * @default COMPLETE
             */
            history_completeness: string;
            /** Latest Snapshot */
            latest_snapshot?: {
                [key: string]: unknown;
            } | null;
            /**
             * Opened At
             * Format: date-time
             */
            opened_at: string;
            /**
             * Pre Entry History Available
             * @default true
             */
            pre_entry_history_available: boolean;
            /**
             * Recovered From Position State
             * @default false
             */
            recovered_from_position_state: boolean;
            /** Recovery Mode */
            recovery_mode?: string | null;
            /** Setup Family */
            setup_family: string;
            /** Symbol Id */
            symbol_id: string;
        };
        /** CandidateSnapshotResponse */
        CandidateSnapshotResponse: {
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            /** Candidate Id */
            candidate_id: string;
            /** Followthrough Status */
            followthrough_status: string;
            /** Lifecycle State */
            lifecycle_state: string;
            /** Snapshot Id */
            snapshot_id: string;
        };
        /** CandidateSummary */
        CandidateSummary: {
            /** Candidate Id */
            candidate_id: string;
            /** Candidate State */
            candidate_state: string;
            /** Closed At */
            closed_at?: string | null;
            /** Exchange */
            exchange: string;
            /** Followthrough Status */
            followthrough_status?: string | null;
            /**
             * History Completeness
             * @default COMPLETE
             */
            history_completeness: string;
            /**
             * Opened At
             * Format: date-time
             */
            opened_at: string;
            /**
             * Pre Entry History Available
             * @default true
             */
            pre_entry_history_available: boolean;
            /**
             * Recovered From Position State
             * @default false
             */
            recovered_from_position_state: boolean;
            /** Recovery Mode */
            recovery_mode?: string | null;
            /** Setup Family */
            setup_family: string;
            /** Symbol Id */
            symbol_id: string;
        };
        /** CorrectionImpactResponse */
        CorrectionImpactResponse: {
            /** Authoritative Calibration Eligible */
            authoritative_calibration_eligible: boolean;
            /** Candidate Id */
            candidate_id?: string | null;
            /** Impact Id */
            impact_id: string;
            /** Impact Link Status */
            impact_link_status: string;
            /** Review Required */
            review_required: boolean;
        };
        /** DecisionContextResponse */
        DecisionContextResponse: {
            /** Action */
            action: string;
            /** Candidate Id */
            candidate_id: string;
            /**
             * Decided At
             * Format: date-time
             */
            decided_at: string;
            /** Decision Context Id */
            decision_context_id: string;
            /** Eligibility */
            eligibility: string;
            /** Reasons */
            reasons?: string[];
        };
        /**
         * FreshnessStatus
         * @enum {string}
         */
        FreshnessStatus: "FRESH" | "STALE" | "UNKNOWN" | "UNAVAILABLE";
        /** GovernanceCorrectionResponse */
        GovernanceCorrectionResponse: {
            /** Authority */
            authority: string;
            /**
             * Available At
             * Format: date-time
             */
            available_at: string;
            /** Governance Event Id */
            governance_event_id: string;
            /** Observation Id */
            observation_id: string;
            /** Policy Version */
            policy_version: string;
            /**
             * Recorded At
             * Format: date-time
             */
            recorded_at: string;
            /** Replacement Observation Id */
            replacement_observation_id?: string | null;
            /** Superseded Observation Id */
            superseded_observation_id?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Api Ready */
            api_ready: boolean;
            /** Limitations */
            limitations: string[];
            /** Optional Sources */
            optional_sources: {
                [key: string]: string;
            };
            /** Phase4 Development Ready */
            phase4_development_ready: boolean;
            /** Phase4 Production Ready */
            phase4_production_ready: boolean;
            /** Primary Source Readable */
            primary_source_readable: boolean;
            /** Source Readable */
            source_readable: boolean;
        };
        /** LineageMeta */
        LineageMeta: {
            primary?: components["schemas"]["LineageRef"] | null;
            /**
             * Source Consistent
             * @default true
             */
            source_consistent: boolean;
            /**
             * Source Version Mismatch
             * @default false
             */
            source_version_mismatch: boolean;
            /** Supporting */
            supporting?: components["schemas"]["LineageRef"][];
        };
        /** LineageRef */
        LineageRef: {
            /** Available At */
            available_at?: string | null;
            /** Content Hash */
            content_hash?: string | null;
            /** Policy Version */
            policy_version?: string | null;
            /** Run Id */
            run_id?: string | null;
            /** Schema Version */
            schema_version?: string | null;
            /** Source As Of */
            source_as_of?: string | null;
            /** Source Id */
            source_id: string;
            /** Source Type */
            source_type: string;
        };
        /** MarketStageResponse */
        MarketStageResponse: {
            /** Conflicts */
            conflicts?: {
                [key: string]: unknown;
            }[];
            /** Observations */
            observations: components["schemas"]["StageObservation"][];
        };
        /** OutcomeAttributionResponse */
        OutcomeAttributionResponse: {
            /** Attribution Id */
            attribution_id: string;
            /** Candidate Id */
            candidate_id: string;
            /** Category */
            category: string;
            /** Confidence */
            confidence: number;
            /**
             * Resolved At
             * Format: date-time
             */
            resolved_at: string;
        };
        /** PaginationMeta */
        PaginationMeta: {
            /**
             * Has More
             * @default false
             */
            has_more: boolean;
            /** Limit */
            limit: number;
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** PerformanceSummaryResponse */
        PerformanceSummaryResponse: {
            /** Artifact Metrics */
            artifact_metrics?: {
                [key: string]: unknown;
            }[];
            /** As Of */
            as_of?: string | null;
            /** Cache Mode */
            cache_mode?: string | null;
            /** Database Metrics */
            database_metrics?: {
                [key: string]: unknown;
            }[];
            /** Database Time Ms */
            database_time_ms?: number | null;
            /** Functional Status */
            functional_status: string;
            /** Operation Metrics */
            operation_metrics?: {
                [key: string]: unknown;
            }[];
            /** Peak Rss Mb */
            peak_rss_mb?: number | null;
            /** Performance Status */
            performance_status: string;
            /** Policy Version */
            policy_version?: string | null;
            /** Replay Comparison */
            replay_comparison?: {
                [key: string]: unknown;
            } | null;
            /** Replay Equivalence */
            replay_equivalence?: string | null;
            /** Replay Mode */
            replay_mode?: string | null;
            /** Rows Processed */
            rows_processed?: number | null;
            /** Run Id */
            run_id: string;
            /** Stage Runtimes */
            stage_runtimes?: {
                [key: string]: number;
            };
            /** Symbols Processed */
            symbols_processed?: number | null;
            /** Threshold Results */
            threshold_results?: {
                [key: string]: unknown;
            }[];
            /** Throughput */
            throughput?: {
                [key: string]: number;
            };
            /** Total Runtime Ms */
            total_runtime_ms?: number | null;
        };
        /** PositionCoverageSummary */
        PositionCoverageSummary: {
            /** Coverage Reasons */
            coverage_reasons?: string[];
            /** Coverage Status */
            coverage_status: string;
            /** Effective Scan Tier */
            effective_scan_tier?: string | null;
            /**
             * Episode Compatibility
             * @default unknown
             */
            episode_compatibility: string;
            /** Episode Match Status */
            episode_match_status?: string | null;
            /**
             * Evidence Complete
             * @default false
             */
            evidence_complete: boolean;
            /** Exchange */
            exchange: string;
            /** Expected Market Session */
            expected_market_session?: string | null;
            /** Investigator Evidence Complete */
            investigator_evidence_complete?: boolean | null;
            /** Last Valid Market Timestamp */
            last_valid_market_timestamp?: string | null;
            /** Market Data Available */
            market_data_available?: boolean | null;
            /**
             * Market Data Complete
             * @default false
             */
            market_data_complete: boolean;
            /** Missing Data Fields */
            missing_data_fields?: string[];
            /** Missing Fields */
            missing_fields?: string[];
            /** Opportunity Episode Id */
            opportunity_episode_id?: string | null;
            /** Policy Version */
            policy_version?: string | null;
            /** Position Cycle Id */
            position_cycle_id: string;
            /**
             * Position Monitor Present
             * @default false
             */
            position_monitor_present: boolean;
            /** Positive Action Suppressed */
            positive_action_suppressed: boolean;
            /** Recovery Status */
            recovery_status?: string | null;
            /** Routing Decision Id */
            routing_decision_id?: string | null;
            /** Suppression Reasons */
            suppression_reasons?: string[];
            /** Symbol Id */
            symbol_id: string;
        };
        /** ReadinessCheckResponse */
        ReadinessCheckResponse: {
            /** Category */
            category: string;
            /** Check Id */
            check_id: string;
            /**
             * Development Blocking
             * @default false
             */
            development_blocking: boolean;
            /** Expected Condition */
            expected_condition?: string | null;
            /** Limitation */
            limitation?: string | null;
            /** Observed Value */
            observed_value?: unknown | null;
            /** Policy Version */
            policy_version?: string | null;
            /**
             * Production Blocking
             * @default false
             */
            production_blocking: boolean;
            /** Remediation */
            remediation?: string | null;
            /**
             * Required For Ready
             * @default false
             */
            required_for_ready: boolean;
            /** Severity */
            severity?: string | null;
            /** Status */
            status: string;
        };
        /** ResponseMeta */
        ResponseMeta: {
            /** As Of */
            as_of?: string | null;
            freshness?: components["schemas"]["SourceFreshness"];
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Limitations */
            limitations?: string[];
            /** Lineage */
            lineage?: components["schemas"]["LineageRef"][];
            lineage_meta?: components["schemas"]["LineageMeta"];
            pagination?: components["schemas"]["PaginationMeta"] | null;
            /**
             * Partial
             * @default false
             */
            partial: boolean;
            /** Request Id */
            request_id: string;
            source_freshness?: components["schemas"]["SourceFreshness"];
        };
        /** RoutingDecisionDetail */
        RoutingDecisionDetail: {
            /**
             * Active Position Structural Risk
             * @default false
             */
            active_position_structural_risk: boolean;
            /** All Reasons */
            all_reasons: string[];
            /**
             * As Of
             * Format: date
             */
            as_of: string;
            /** Decision Id */
            decision_id: string;
            /** Effective Scan Tier */
            effective_scan_tier: string;
            /** Exchange */
            exchange: string;
            /** Lineage */
            lineage?: components["schemas"]["LineageRef"][];
            /**
             * New Long Structural Block
             * @default false
             */
            new_long_structural_block: boolean;
            /** Policy Version */
            policy_version: string;
            /** Risk Severity */
            risk_severity?: string | null;
            /** Routing Input Hash */
            routing_input_hash?: string | null;
            /** Selection Details */
            selection_details?: {
                [key: string]: unknown;
            }[];
            /** Symbol Id */
            symbol_id: string;
            /** Winning Reason */
            winning_reason: string;
        };
        /** RoutingDecisionSummary */
        RoutingDecisionSummary: {
            /**
             * Active Position Structural Risk
             * @default false
             */
            active_position_structural_risk: boolean;
            /** All Reasons */
            all_reasons: string[];
            /**
             * As Of
             * Format: date
             */
            as_of: string;
            /** Decision Id */
            decision_id: string;
            /** Effective Scan Tier */
            effective_scan_tier: string;
            /** Exchange */
            exchange: string;
            /**
             * New Long Structural Block
             * @default false
             */
            new_long_structural_block: boolean;
            /** Policy Version */
            policy_version: string;
            /** Risk Severity */
            risk_severity?: string | null;
            /** Routing Input Hash */
            routing_input_hash?: string | null;
            /** Symbol Id */
            symbol_id: string;
            /** Winning Reason */
            winning_reason: string;
        };
        /** SectorSummary */
        SectorSummary: {
            /** As Of */
            as_of?: string | null;
            /** Available At */
            available_at?: string | null;
            /** Effective Stage */
            effective_stage: string;
            /** Exchange */
            exchange?: string | null;
            /**
             * Governance Status
             * @default AUTHORITATIVE
             */
            governance_status: string;
            /** Membership Trust */
            membership_trust?: string | null;
            /** Observation Id */
            observation_id: string;
            /** Sector Id */
            sector_id?: string | null;
            /** Sector Name */
            sector_name?: string | null;
            /** Source Week End */
            source_week_end?: string | null;
            /** Source Week Start */
            source_week_start?: string | null;
            /** Stage Confidence */
            stage_confidence?: number | null;
            /** Stage Status */
            stage_status: string;
            /** Supersedes Observation Id */
            supersedes_observation_id?: string | null;
            /** Symbol Id */
            symbol_id?: string | null;
        };
        /** SourceFreshness */
        SourceFreshness: {
            /** Expected Market Session */
            expected_market_session?: string | null;
            /** Freshness Reasons */
            freshness_reasons?: string[];
            /** @default UNKNOWN */
            freshness_status: components["schemas"]["FreshnessStatus"];
            /** Last Successful Run At */
            last_successful_run_at?: string | null;
            /** Latest Market Session */
            latest_market_session?: string | null;
            /** Source As Of */
            source_as_of?: string | null;
            /** Staleness Sessions */
            staleness_sessions?: number | null;
        };
        /** StageObservation */
        StageObservation: {
            /** As Of */
            as_of?: string | null;
            /** Available At */
            available_at?: string | null;
            /** Effective Stage */
            effective_stage: string;
            /** Exchange */
            exchange?: string | null;
            /**
             * Governance Status
             * @default AUTHORITATIVE
             */
            governance_status: string;
            /** Membership Trust */
            membership_trust?: string | null;
            /** Observation Id */
            observation_id: string;
            /** Sector Id */
            sector_id?: string | null;
            /** Sector Name */
            sector_name?: string | null;
            /** Source Week End */
            source_week_end?: string | null;
            /** Source Week Start */
            source_week_start?: string | null;
            /** Stage Confidence */
            stage_confidence?: number | null;
            /** Stage Status */
            stage_status: string;
            /** Supersedes Observation Id */
            supersedes_observation_id?: string | null;
            /** Symbol Id */
            symbol_id?: string | null;
        };
        /** StockSummary */
        StockSummary: {
            /** As Of */
            as_of?: string | null;
            /** Available At */
            available_at?: string | null;
            /** Effective Stage */
            effective_stage: string;
            /** Exchange */
            exchange?: string | null;
            /**
             * Governance Status
             * @default AUTHORITATIVE
             */
            governance_status: string;
            /** Membership Trust */
            membership_trust?: string | null;
            /** Observation Id */
            observation_id: string;
            /** Sector Id */
            sector_id?: string | null;
            /** Sector Name */
            sector_name?: string | null;
            /** Sector Stage */
            sector_stage?: string | null;
            /** Source Week End */
            source_week_end?: string | null;
            /** Source Week Start */
            source_week_start?: string | null;
            /** Stage Confidence */
            stage_confidence?: number | null;
            /** Stage Status */
            stage_status: string;
            /** Supersedes Observation Id */
            supersedes_observation_id?: string | null;
            /** Symbol Id */
            symbol_id?: string | null;
        };
        /** SystemLimitation */
        SystemLimitation: {
            /** Description */
            description: string;
            /**
             * Development Blocking
             * @default false
             */
            development_blocking: boolean;
            /** Limitation Id */
            limitation_id: string;
            /**
             * Production Blocking
             * @default true
             */
            production_blocking: boolean;
            /** Remediation */
            remediation?: string | null;
            /**
             * Severity
             * @default warning
             */
            severity: string;
        };
        /** SystemReadinessResponse */
        SystemReadinessResponse: {
            /** Limitations */
            limitations: components["schemas"]["SystemLimitation"][];
            /** Phase4 Development Ready */
            phase4_development_ready: boolean;
            /** Phase4 Production Ready */
            phase4_production_ready: boolean;
            /** Readiness Status */
            readiness_status: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VersionResponse */
        VersionResponse: {
            /** Api Version */
            api_version: string;
            /** Application Version */
            application_version: string;
            /** Calibration Policy Version */
            calibration_policy_version: string;
            /** Git Commit */
            git_commit: string;
            /** Performance Policy Version */
            performance_policy_version: string;
            /** Readiness Policy Version */
            readiness_policy_version: string;
            /** Routing Policy Version */
            routing_policy_version: string;
            /** Schema Version */
            schema_version: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    incidents_api_v1_alert_incidents_get: {
        parameters: {
            query?: {
                severity?: string | null;
                status?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_list_AlertIncidentSummary__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    incident_detail_api_v1_alert_incidents__incident_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_AlertIncidentSummary_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    alerts_api_v1_alerts_get: {
        parameters: {
            query?: {
                severity?: string | null;
                status?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_list_AlertSummary__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    alert_detail_api_v1_alerts__alert_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alert_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_AlertSummary_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    calibration_coverage_api_v1_calibration_coverage_get: {
        parameters: {
            query?: {
                dimension?: string | null;
                bucket?: string | null;
                status?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_list_dict_str__Any___"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    calibration_exclusions_api_v1_calibration_exclusions_get: {
        parameters: {
            query?: {
                eligibility_status?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_list_dict_str__Any___"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    calibration_manifest_api_v1_calibration_manifest_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_CalibrationManifestResponse_"];
                };
            };
        };
    };
    calibration_summary_api_v1_calibration_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_CalibrationSummaryResponse_"];
                };
            };
        };
    };
    candidates_api_v1_candidates_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
                sort?: string;
                order?: string;
                symbol?: string | null;
                candidate_state?: string | null;
                setup_family?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_list_CandidateSummary__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    candidate_detail_api_v1_candidates__candidate_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                candidate_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_CandidateDetail_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    candidate_decisions_api_v1_candidates__candidate_id__decisions_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path: {
                candidate_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_list_DecisionContextResponse__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    candidate_outcomes_api_v1_candidates__candidate_id__outcomes_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path: {
                candidate_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_list_OutcomeAttributionResponse__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    candidate_snapshots_api_v1_candidates__candidate_id__snapshots_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path: {
                candidate_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_list_CandidateSnapshotResponse__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    governance_conflicts_api_v1_governance_conflicts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_list_dict_str__Any___"];
                };
            };
        };
    };
    impacts_api_v1_governance_correction_impacts_get: {
        parameters: {
            query?: {
                status?: string | null;
                review_required?: boolean | null;
                calibration_eligible?: boolean | null;
                entity_type?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_list_CorrectionImpactResponse__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    memberships_api_v1_governance_membership_history_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_list_dict_str__Any___"];
                };
            };
        };
    };
    corrections_api_v1_governance_stage_corrections_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_list_GovernanceCorrectionResponse__"];
                };
            };
        };
    };
    health_live_api_v1_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_dict_str__str__"];
                };
            };
        };
    };
    health_ready_api_v1_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_HealthResponse_"];
                };
            };
        };
    };
    market_stage_api_v1_market_stage_get: {
        parameters: {
            query?: {
                as_of?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_MarketStageResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    performance_baselines_api_v1_performance_baselines_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_list_PerformanceSummaryResponse__"];
                };
            };
        };
    };
    performance_latest_api_v1_performance_latest_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_PerformanceSummaryResponse_"];
                };
            };
        };
    };
    performance_runs_api_v1_performance_runs_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
                sort?: string;
                order?: string;
                cache_mode?: string | null;
                replay_mode?: string | null;
                performance_status?: string | null;
                date_from?: string | null;
                date_to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_list_PerformanceSummaryResponse__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    performance_run_api_v1_performance_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_PerformanceSummaryResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    position_coverage_api_v1_positions_coverage_get: {
        parameters: {
            query?: {
                coverage_status?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_list_PositionCoverageSummary__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    position_detail_api_v1_positions_coverage__position_cycle_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                position_cycle_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_PositionCoverageSummary_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    position_missing_api_v1_positions_missing_data_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_list_dict_str__Any___"];
                };
            };
        };
    };
    recovery_proposals_api_v1_positions_recovery_proposals_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_list_dict_str__Any___"];
                };
            };
        };
    };
    readiness_checks_api_v1_readiness_checks_get: {
        parameters: {
            query?: {
                readiness_status?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_list_ReadinessCheckResponse__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    routing_api_v1_routing_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
                sort?: string;
                order?: string;
                symbol?: string | null;
                scan_tier?: string | null;
                scan_reason?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_list_RoutingDecisionSummary__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    routing_conflicts_api_v1_routing_conflicts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_list_dict_str__Any___"];
                };
            };
        };
    };
    routing_detail_api_v1_routing__routing_decision_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                routing_decision_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_RoutingDecisionDetail_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sectors_api_v1_sectors_get: {
        parameters: {
            query?: {
                as_of?: string | null;
                sector_stage?: string | null;
                stage_status?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_list_SectorSummary__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sector_detail_api_v1_sectors__sector_id__get: {
        parameters: {
            query?: {
                as_of?: string | null;
            };
            header?: never;
            path: {
                sector_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_SectorSummary_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stocks_api_v1_stocks_get: {
        parameters: {
            query?: {
                as_of?: string | null;
                symbol?: string | null;
                sector?: string | null;
                stock_stage?: string | null;
                stage_status?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_list_StockSummary__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stock_detail_api_v1_stocks__symbol_id__get: {
        parameters: {
            query?: {
                as_of?: string | null;
            };
            header?: never;
            path: {
                symbol_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_StockSummary_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stock_routing_api_v1_stocks__symbol_id__routing_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                symbol_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_list_RoutingDecisionSummary__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stock_history_api_v1_stocks__symbol_id__stage_history_get: {
        parameters: {
            query?: {
                as_of?: string | null;
            };
            header?: never;
            path: {
                symbol_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_list_StageObservation__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    system_limitations_api_v1_system_limitations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_list_SystemLimitation__"];
                };
            };
        };
    };
    system_readiness_api_v1_system_readiness_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_SystemReadinessResponse_"];
                };
            };
        };
    };
    system_version_api_v1_system_version_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_VersionResponse_"];
                };
            };
        };
    };
}
