"""Stable Phase 4A limitation-code registry."""

from __future__ import annotations


LIMITATION_CODES = frozenset({
    "SOURCE_NOT_MIGRATED", "SOURCE_EMPTY", "SOURCE_UNAVAILABLE",
    "SOURCE_VERSION_MISMATCH", "LINEAGE_UNAVAILABLE", "FRESHNESS_UNKNOWN",
    "POSITION_COVERAGE_ARTIFACT_MISSING",
    "POSITION_RECONCILIATION_ARTIFACT_MISSING",
    "POSITION_RECOVERY_ACTIONS_UNAVAILABLE", "POSITION_COMPATIBILITY_UNAVAILABLE",
    "CALIBRATION_MANIFEST_MISSING", "CALIBRATION_COVERAGE_MISSING",
    "CALIBRATION_EXCLUSIONS_MISSING", "READINESS_CHECKS_MISSING",
    "PERFORMANCE_SUMMARY_MISSING", "PERFORMANCE_METRICS_MISSING",
    "PERFORMANCE_DATABASE_METRICS_MISSING", "PERFORMANCE_ARTIFACT_METRICS_MISSING",
    "REPLAY_COMPARISON_MISSING", "COPIED_REALISTIC_BASELINE_MISSING",
    "GOVERNANCE_CONFLICT_PRESENT", "EMPTY_REAL_PHASE3B_HISTORY",
    "OPERATOR_MIGRATIONS_NOT_APPLIED", "SINGLE_YEAR_CONCENTRATION",
})

PRODUCTION_LIMITATIONS = (
    "SINGLE_YEAR_CONCENTRATION",
    "COPIED_REALISTIC_BASELINE_MISSING",
    "OPERATOR_MIGRATIONS_NOT_APPLIED",
    "EMPTY_REAL_PHASE3B_HISTORY",
)


def normalized_limitations(values: list[str] | tuple[str, ...]) -> list[str]:
    """Return unique registered codes in stable order."""
    return list(dict.fromkeys(value for value in values if value in LIMITATION_CODES))
