"""Shared execution models for paper and broker-backed order flows."""

from __future__ import annotations

from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from typing import Any, Dict, Optional


def utcnow() -> datetime:
    """Return a timezone-aware UTC timestamp."""
    return datetime.now(timezone.utc)


@dataclass(slots=True)
class OrderIntent:
    """Normalized order request used by all execution adapters."""

    symbol_id: str
    quantity: int
    side: str = "BUY"
    exchange: str = "NSE"
    order_type: str = "MARKET"
    product_type: str = "INTRADAY"
    validity: str = "DAY"
    limit_price: Optional[float] = None
    stop_price: Optional[float] = None
    requested_price: Optional[float] = None
    correlation_id: Optional[str] = None
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass(slots=True)
class OrderRecord:
    """Persisted order state."""

    order_id: str
    broker: str
    symbol_id: str
    quantity: int
    side: str
    exchange: str
    order_type: str
    product_type: str
    validity: str
    status: str
    submitted_at: datetime
    updated_at: datetime
    correlation_id: Optional[str] = None
    broker_order_id: Optional[str] = None
    limit_price: Optional[float] = None
    stop_price: Optional[float] = None
    requested_price: Optional[float] = None
    avg_fill_price: Optional[float] = None
    filled_quantity: int = 0
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        payload = asdict(self)
        payload["submitted_at"] = self.submitted_at.isoformat()
        payload["updated_at"] = self.updated_at.isoformat()
        return payload


@dataclass(slots=True)
class FillRecord:
    """Persisted fill event."""

    fill_id: str
    order_id: str
    broker: str
    symbol_id: str
    quantity: int
    price: float
    filled_at: datetime
    side: str
    exchange: str
    broker_fill_id: Optional[str] = None
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        payload = asdict(self)
        payload["filled_at"] = self.filled_at.isoformat()
        return payload


@dataclass(slots=True)
class TradeAction:
    """High-level trading action generated by strategy policies."""

    action: str
    symbol_id: str
    exchange: str = "NSE"
    side: str = "BUY"
    quantity: Optional[int] = None
    requested_price: Optional[float] = None
    strategy_mode: str = "technical"
    reason: str = ""
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)
