"""Shared contracts for the fundamentals domain."""

from __future__ import annotations

FUNDAMENTAL_SCORE_COLUMNS = [
    "quality_score",
    "growth_score",
    "balance_sheet_score",
    "valuation_score",
    "ownership_score",
    "fundamental_score",
]

FUNDAMENTAL_OUTPUT_COLUMNS = [
    "snapshot_date",
    "symbol",
    "name",
    "industry_group",
    "industry",
    *FUNDAMENTAL_SCORE_COLUMNS,
    "fundamental_tier",
    "red_flags",
    "hard_red_flag",
    "screener_snapshot_date",
]

INDUSTRY_FUNDAMENTAL_SCORE_COLUMNS = [
    "industry_growth_score",
    "industry_quality_score",
    "industry_valuation_score",
    "industry_momentum_score",
    "industry_fundamental_score",
]

INDUSTRY_FUNDAMENTAL_OUTPUT_COLUMNS = [
    "snapshot_date",
    "industry",
    "industry_key",
    "no_of_companies",
    "total_market_cap",
    "median_market_cap",
    "median_pe",
    "sales_growth_wavg",
    "opm_wavg",
    "roce_wavg",
    "median_1y_return",
    *INDUSTRY_FUNDAMENTAL_SCORE_COLUMNS,
    "industry_fundamental_label",
    "industry_warning",
    "screener_industry_snapshot_date",
]

WATCHLIST_BUCKET_PRIORITY = {
    "F4_ACTION_CANDIDATE": 0,
    "F3_FUND_VALUE_TECH_READY": 1,
    "F2_RESULT_VALUE_ACCUMULATION": 2,
    "F1_FUNDAMENTAL_WATCH": 3,
    "D1_RESULT_DOWNTURN": 4,
    "D2_AVOID_RED_FLAG": 5,
    "IGNORE_FOR_NOW": 6,
    "ADD_TO_WATCHLIST": 10,
    "STUDY_ONLY": 11,
    "TECHNICAL_ONLY_RISK": 12,
    "AVOID_RED_FLAG": 13,
}

WATCHLIST_OUTPUT_COLUMNS = [
    "symbol",
    "name",
    "industry_group",
    "industry",
    "composite_score",
    "relative_strength",
    "volume_intensity",
    "trend_persistence",
    "proximity_to_highs",
    "delivery_pct",
    "sector_strength",
    "breakout_type",
    "breakout_score",
    "candidate_tier",
    "qualified",
    "pattern_family",
    "pattern_state",
    "pattern_score",
    "setup_quality",
    "quality_score",
    "growth_score",
    "balance_sheet_score",
    "valuation_score",
    "ownership_score",
    "fundamental_score",
    "fundamental_tier",
    "red_flags",
    "hard_red_flag",
    "fundamental_score_delta",
    "fundamental_trend_label",
    "trend_reason",
    "industry_fundamental_score",
    "industry_growth_score",
    "industry_quality_score",
    "industry_valuation_score",
    "industry_momentum_score",
    "industry_fundamental_label",
    "industry_warning",
    "industry_score_delta",
    "industry_trend_label",
    "catalyst_score",
    "catalyst_type",
    "catalyst_summary",
    "evidence_source",
    "confidence",
    "report_date",
    "available_at",
    "sales_yoy_pct",
    "sales_qoq_pct",
    "operating_profit_yoy_pct",
    "operating_profit_qoq_pct",
    "profit_yoy_pct",
    "profit_qoq_pct",
    "opm_pct",
    "opm_yoy_change_bps",
    "opm_qoq_change_bps",
    "quarterly_result_score",
    "quarterly_result_bucket",
    "quarterly_result_reason",
    "low_base_flag",
    "margin_expansion_flag",
    "quality_penalty",
    "pe_ttm",
    "ps_ttm",
    "pb",
    "pe_median_3y",
    "pe_median_5y",
    "ps_median_3y",
    "ps_median_5y",
    "pb_median_3y",
    "pb_median_5y",
    "pe_pctile_3y",
    "pe_pctile_5y",
    "ps_pctile_3y",
    "ps_pctile_5y",
    "pb_pctile_3y",
    "pb_pctile_5y",
    "pe_vs_3y_median_pct",
    "pe_vs_5y_median_pct",
    "ps_vs_3y_median_pct",
    "ps_vs_5y_median_pct",
    "pb_vs_3y_median_pct",
    "pb_vs_5y_median_pct",
    "valuation_history_score",
    "valuation_history_bucket",
    "valuation_reason",
    "final_watchlist_score",
    "watchlist_bucket",
    "watchlist_reason",
    "next_action",
]
