"""FastAPI routers for the execution console API."""

from ai_trading_system.ui.execution_api.routes import (
    artifacts,
    backtest,
    decision_history,
    fundamentals,
    health,
    insight,
    investigator,
    optimization,
    perf_tracker,
    pipeline,
    processes,
    ranking_detail,
    runs,
    sectors,
    snapshots,
    stocks,
    tasks,
)

ALL_ROUTERS = (
    health.router,
    fundamentals.router,
    insight.router,
    investigator.router,
    snapshots.router,
    runs.router,
    artifacts.router,
    stocks.router,
    ranking_detail.router,
    tasks.router,
    processes.router,
    pipeline.router,
    sectors.router,
    backtest.router,
    perf_tracker.router,
    optimization.router,
    decision_history.router,
    decision_history.diagnostics_router,
)


__all__ = [
    "ALL_ROUTERS",
    "artifacts",
    "backtest",
    "decision_history",
    "fundamentals",
    "health",
    "insight",
    "investigator",
    "optimization",
    "perf_tracker",
    "pipeline",
    "processes",
    "ranking_detail",
    "runs",
    "sectors",
    "snapshots",
    "stocks",
    "tasks",
]
